language: java
jdk:
- oraclejdk8
- oraclejdk7
env:
  global:
  - secure: SmyaV4ZzuAwS9qPmZuQm8Gm2UsRbKvsxPAUU4DkQM9UX4yR0x4RPRrsPC8rKhaAq5V6IdkBHJhpWTtdqkMQAQRD3eiNKjDAfYNOG3RdU8cOy1YxnGDfJn1iYJ49ntw9HCXXkJVuCdF9oNehFvgxJg2OW/iTB14FNkrE1JIf4WlU=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- ".utility/push-output-to-ghpages.sh"
