language: java

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: oraclejdk9
    - jdk: oraclejdk8

env:
  global:
  - secure: SmyaV4ZzuAwS9qPmZuQm8Gm2UsRbKvsxPAUU4DkQM9UX4yR0x4RPRrsPC8rKhaAq5V6IdkBHJhpWTtdqkMQAQRD3eiNKjDAfYNOG3RdU8cOy1YxnGDfJn1iYJ49ntw9HCXXkJVuCdF9oNehFvgxJg2OW/iTB14FNkrE1JIf4WlU=
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - ".utility/push-output-to-ghpages.sh"